name: Unzip and Deploy  
on:  
  push  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Repo  
        uses: actions/checkout@v2  
        
      - name: Unzip Files  
        run: unzip DiscordInquirer-1-1.zip -d extracted_folder  
        
      - name: Move Files to Root  
        run: mv extracted_folder/* . && rm -rf extracted_folder DiscordInquirer-1-1.zip  

      - name: Install Railway CLI  
        run: curl -fsSL https://railway.app/install.sh | sh  

      - name: Deploy to Railway  
        run: railway up  
        env:  
          RAILWAY_TOKEN: ${{ e496de46-981c-48e2-9c38-80f2ee09e81a }}
